"""empty message

Revision ID: eb7f9ed9945c
Revises: None
Create Date: 2016-08-16 14:34:23.686000

"""

# revision identifiers, used by Alembic.
revision = 'eb7f9ed9945c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_create_time'), 'articles', ['create_time'], unique=False)
    op.drop_index('ix_articles_creat_time', table_name='articles')
    op.drop_column('articles', 'creat_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('creat_time', sa.DATETIME(), nullable=True))
    op.create_index('ix_articles_creat_time', 'articles', ['creat_time'], unique=False)
    op.drop_index(op.f('ix_articles_create_time'), table_name='articles')
    op.drop_column('articles', 'create_time')
    ### end Alembic commands ###
